config/routes.rb
Rails.application.routes.draw do
  root 'chatters#index'
  resources :chatters
  post '/', to: 'chatters#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chatter.rb
class Chatter < ApplicationRecord
    validates :content, length: { in:1..140 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/chatters_controller.rb
class ChattersController < ApplicationController
  before_action :chatter_order, only: [:index, :create]
  before_action :set_chatter, only: [:edit, :update, :destroy]

  def index
    @chatter = Chatter.new
  end

  def create
    @chatter = Chatter.create(chatter_params)
    if @chatter.save
      redirect_to root_path, notice: "ツイートを投稿しました！"
    else
      render :index
    end
  end

  def edit
  end

  def update
    if @chatter.update(chatter_params)
      redirect_to root_path, notice: "ツイートを更新しました！"
    else
      render :edit
    end
  end

  def destroy
    @chatter.destroy
    redirect_to root_path, notice: "ツイートを削除しました！"
  end

  private

  def set_chatter
    @chatter = Chatter.find(params[:id])
  end

  def chatter_params
    params.require(:chatter).permit(:content)
  end

  def chatter_order
    @chatters = Chatter.all.order('id DESC')
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatters_helper.rb
module ChattersHelper
    def choose_new_or_edit
        if action_name == 'create' || action_name == 'index' ||
            root_path
        elsif action_name == 'edit'
            chatter_path
        end
    end
end

app/views/chatters/_form.html.erb
<%= form_with(model: @chatter, local: true, url: choose_new_or_edit) do |form| %>
    <% if @chatter.errors.any? %>
        <ul class="error_messages">
            <% @chatter.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
    <% end %>
    <div class="chatter_content">
        <%= form.label :content %>
        <%= form.text_field :content %>
    </div>
    <%= form.submit %>
<% end %>

app/views/chatters/edit.html.erb
<!DOCTYPE html>
<html lang="jp">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>ChatterApp</title>
</head>

<body>
    <header>
    </header>

    <article>
        <section>
            <h1>ChatterApp</h1>
            <%= render 'form' %>
            <p><%= notice %></p>
        </section>
    </article>

    <footer>
    </footer>

</body>
</html>

app/views/chatters/index.html.erb
<!DOCTYPE html>
<html lang="jp">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>ChatterApp</title>
</head>

<body>
    <header>
    </header>

    <article>
        <section>
            <h1>ChatterApp</h1>
            <%= render 'form' %>
            <p><%= notice %></p>
        </section>
    </article>

<hr>

    <article>
        <section>
            <% @chatters.each do |chatter| %>
                <div>
                    <%= chatter.content %>
                </div>
                <div class="edit_botton">
                    <%= link_to '編集', edit_chatter_path(chatter.id) %>
                </div>
                <div class="edit_botton">
                    <%= link_to '削除', chatter_path(chatter.id), method: :delete, data: { confirm: '本当に削除してよろしいですか？' } %>
                </div>
            <% end %>
        </section>
    </article>

    <footer>
    </footer>

</body>
</html>

app/views/chatters/new.html.erb
<!DOCTYPE html>
<html lang="jp">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>ChatterApp</title>
</head>
<body>
    <h1>NEW</h1>

    
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chatterapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>